### ISSUE TITLE
We dont need any separate ErrorController

### ISSUE THREAD

**Issue by Reddy57** [Antra-Inc/Aura-HCM#3]
https://github.com/Antra-Inc/Aura-HCM/blob/71992d6059e94abfb8f1cb7005a907eab6594a45/src/Aura.API/Controllers/ErrorController.cs#L9

We don't need any separate ErrorController,  in ASP.NET Core we create custom Exception Middleware and configure it in the startup file

**Comment by clu005** [comment]
Was following document here: https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1
Tested working, and looks like it is automatically using the middleware.
